version: 1.2
workflows:
  - name: myco_raw
    subclass: WDL
    primaryDescriptorPath: /myco_raw.wdl
    readMePath: /doc/myco_raw.md
    authors:
      - orcid: 0000-0003-4896-1858
  - name: myco_sra
    subclass: WDL
    primaryDescriptorPath: /myco_sra.wdl
    readMePath: /doc/myco_sra.md
    testParameterFiles:
      - /inputs/myco_sra_terra.json
      - /inputs/myco_sra_local.json
    authors:
      - orcid: 0000-0003-4896-1858
  - name: myco_simple
    subclass: WDL
    primaryDescriptorPath: /myco_simple.wdl
    readMePath: /doc/myco_simple.md
    authors:
      - orcid: 0000-0003-4896-1858
  - name: myco_wrapper_example
    subclass: WDL
    primaryDescriptorPath: /wrapper_example.wdl
    readMePath: /doc/wrapper_example.md
    authors:
      - orcid: 0000-0003-4896-1858
