version: 1.2
workflows:
  - name: myco
    subclass: WDL
    primaryDescriptorPath: /myco.wdl
    authors:
      - orcid: 0000-0003-4896-1858
  - name: myco_sra
    subclass: WDL
    primaryDescriptorPath: /myco_sra.wdl
    readMePath: /doc/myco_sra.wdl
    authors:
      - orcid: 0000-0003-4896-1858